version: '2'

services:
  postgresql:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: waste-tracing_password
      POSTGRES_USER: waste-tracing_user
      POSTGRES_DB: waste-tracing
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '8585:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: waste@tracing.it
      PGADMIN_DEFAULT_PASSWORD: tracing
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data