name: Maven & Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile, Build Native, Build Docker Image, Push on Github
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Maven Package
        run: mvn clean package -DskipTests=true 
        
      - name: Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          contextName: src/main/docker/Dockerfile.jvm
          tag: |
            latest
            ${{ github.sha }} 
